defaults:
  - _self_
  - task: jackal_lowdim

name: train_mlp_lowdim
_target_: jackal_diffusion.workspace.train_mlp_lowdim_workspace.TrainMlpLowdimWorkspace

task_name: ${task.name}
exp_name: default
obs_dim: ${task.obs_dim}
action_dim: ${task.action_dim}

n_obs_steps: 2
n_action_steps: 8

policy:
  _target_: jackal_diffusion.policy.jackal_mlp_lowdim_policy.JackalMLPLowdimPolicy
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  hidden_dim: 256

dataloader:
  batch_size: 64
  num_workers: 0
  shuffle: True
  pin_memory: False

val_dataloader:
  batch_size: 64
  num_workers: 0
  shuffle: False
  pin_memory: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-3
  weight_decay: 1.0e-6

training:
  device: cpu
  seed: 42
  debug: False
  resume: False
  num_epochs: 500
  gradient_accumulate_every: 1
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  max_train_steps: null
  max_val_steps: null
  early_stop_loss: 0.001

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 3
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
  save_last_ckpt: True
  save_last_snapshot: False

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
